[project]
name = "kraken"

[bin]
main = "src/Main.saga"

[library]
module = "Kraken"
expose = ["Kraken.Db", "Kraken.Core", "Kraken.Query", "Kraken.Write"]

[deps]
saga_pgo = { path = "../saga_pgo" }
saga_json = { path = "../saga_json" }
